//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbTeknıkServısEntities : DbContext
    {
        public DbTeknıkServısEntities()
            : base("name=DbTeknıkServısEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBL_ADMIN> TBL_ADMIN { get; set; }
        public virtual DbSet<TBL_ARACLAR> TBL_ARACLAR { get; set; }
        public virtual DbSet<TBL_ARIZADETAY> TBL_ARIZADETAY { get; set; }
        public virtual DbSet<TBL_CARI> TBL_CARI { get; set; }
        public virtual DbSet<TBL_DEPARTMAN> TBL_DEPARTMAN { get; set; }
        public virtual DbSet<TBL_FATURABILGI> TBL_FATURABILGI { get; set; }
        public virtual DbSet<TBL_FATURADETAY> TBL_FATURADETAY { get; set; }
        public virtual DbSet<TBL_GIDER> TBL_GIDER { get; set; }
        public virtual DbSet<TBL_HAKKIMIZDA> TBL_HAKKIMIZDA { get; set; }
        public virtual DbSet<TBL_HAREKET> TBL_HAREKET { get; set; }
        public virtual DbSet<TBL_İLETİSİM> TBL_İLETİSİM { get; set; }
        public virtual DbSet<TBL_KATEGORI> TBL_KATEGORI { get; set; }
        public virtual DbSet<TBL_NOTLAR> TBL_NOTLAR { get; set; }
        public virtual DbSet<TBL_PERSONEL> TBL_PERSONEL { get; set; }
        public virtual DbSet<TBL_URUN> TBL_URUN { get; set; }
        public virtual DbSet<TBL_URUNKABUL> TBL_URUNKABUL { get; set; }
        public virtual DbSet<TBL_URUNTAKIP> TBL_URUNTAKIP { get; set; }
        public virtual DbSet<İL> İL { get; set; }
        public virtual DbSet<İLCE> İLCE { get; set; }
    
        public virtual ObjectResult<URUNKATEGORİ_Result> URUNKATEGORİ()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<URUNKATEGORİ_Result>("URUNKATEGORİ");
        }
    
        public virtual ObjectResult<string> MAKSKATEGORİ()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MAKSKATEGORİ");
        }
    
        public virtual ObjectResult<string> MAKSURUNMARKA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MAKSURUNMARKA");
        }
    
        public virtual ObjectResult<string> MAXIL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MAXIL");
        }
    
        public virtual ObjectResult<string> MAKSDEPARTMAN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MAKSDEPARTMAN");
        }
    
        public virtual ObjectResult<string> MİNDEPARTMAN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MİNDEPARTMAN");
        }
    }
}
